### ISSUE TITLE
能否加入 选择性显示功能（Filter text）

### ISSUE THREAD

**Issue by JamesJian-tech** [xenkuo/comNG#11]
平时使用terminal 信息很多 如果有一个过滤功能就很方便了 例如：

[time] hello hello
[time] hello
[time] hello
[time] hello
[time] hello
[time] world 
[time] hello
[time] hello
[time] hello
[time] hello

其实只想知道 world 的出现点和时间  其他的hello 并不需要在terminal 里面出现 但可以存在.log 文件里面。

能否实现？

**Comment by xenkuo** [comment]
目前没有完全一致的功能。
技术上应该可以实现，不过我可能没这个技术 :)
