### ISSUE TITLE
工具打开是空白的，Win7x64 (No content shown after run comNG in windows7)

### ISSUE THREAD

**Issue by Femtometer** [xenkuo/comNG#8]
Click setting or close button no response.
Screen shot:
![image](https://user-images.githubusercontent.com/5461891/146472885-b95855e2-024e-4894-88db-fb9dc692590e.png)

**Comment by xenkuo** [comment]
Did you run comNG directly from source code? In this condition, you need to change **mode** from `prd` to `dev`. With latest code, should have no this problem.

**Comment by Femtometer** [comment]
> Did you run comNG directly from source code? In this condition, you need to change **mode** from `prd` to `dev`. With latest code, should have no this problem.

No, I downloaded Setup.exe on release 2.1.1 and install.

**Comment by xenkuo** [comment]
我没在Win7上试过，可能是平台部兼容？

**Comment by xenkuo** [comment]
试一下最新的release，用一个版本号，之前的release我配置错了一个信息。

**Comment by Femtometer** [comment]
Fixed in lastest release.
