### ISSUE TITLE
v2.1.1版本安装后无法使用

### ISSUE THREAD

**Issue by 2622019635** [xenkuo/comNG#9]
系统：Windows 11
状况：安装完成后打开软件，软件各部分点击无效，只有开关可以点击。

**Comment by xenkuo** [comment]
Win11我还没测试过，可能是有些库不支持。Win10上我用的没问题，之前的版本你在Win11上试过吗？

**Comment by 2622019635** [comment]
现在还是一直用的是前一个版本，非常好用漂亮 @xenkuo

**Comment by xenkuo** [comment]
可以试下最新的2.1.1，应该好了。
